# Generated by Django 3.2.7 on 2021-09-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deptartment',
            new_name='Department',
        ),
    ]
