# Generated by Django 3.2.7 on 2021-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0002_rename_deptartment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='dept',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='dept',
            field=models.ManyToManyField(to='Information.Department'),
        ),
    ]
