# Generated by Django 3.2.7 on 2021-09-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0003_auto_20210910_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='dept',
            new_name='Dept_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dept',
            new_name='Dept_name',
        ),
    ]
