# Generated by Django 3.2.7 on 2021-09-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0004_auto_20210911_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.department')),
                ('lecturername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.lecturer')),
            ],
        ),
    ]
